openapi: 3.0.3
info:
  title: STD24013
  description: This is a specification of STD24013
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /health:
    get:
      summary: Check health
      responses:
        '200':
          description: Returns Ok
          content:
            text/plain:
              schema:
                type: string
                example: Ok

  /phones:
    post:
      summary: Create a phone
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Phone'
      responses:
        '201':
          description: Phone created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Phone'
    get:
      summary: Get all phones
      responses:
        '200':
          description: List of phones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Phone'

  /phones/{id}:
    get:
      summary: Get a phone by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A phone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Phone'
        '404':
          description: Phone not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
components:
  schemas:
    Characteristic:
      type: object
      properties:
        ram_memory:
          type: integer
        rom_memory:
          type: integer
      required: [ ram_memory, rom_memory ]
      example:
        ram_memory: 8
        rom_memory: 128

    Phone:
      type: object
      properties:
        identifier:
          type: string
        brand:
          type: string
        model:
          type: string
        characteristics:
          $ref: '#/components/schemas/Characteristic'
      required: [ identifier, brand, model, characteristics ]
      example:
        identifier: phone1
        brand: Samsung
        model: Galaxy S23
        characteristics:
          ram_memory: 8
          rom_memory: 128


